### ISSUE TITLE
improve the design / layout of the website

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/projectevergreen.github.io#3]
anything would probably be better than what's there now 😊

**Comment by thescientist13** [comment]
@Aimeelynnramirez 
That would be great!  I have no strong preference either way about layout / design.  Feel free to comment with a mockup or any proposal / ideas you have in mind, I'm sure they will be awesome!  ⭐️

**Comment by Aimeelynnramirez** [comment]
<img width="395" alt="mockup" src="https://user-images.githubusercontent.com/29737299/44976578-9f8fe280-af33-11e8-93b1-0bd4714f52de.png">
Here I'm creating a idea for a sidebar to appear with content list of your choosing. 

<img width="397" alt="actual" src="https://user-images.githubusercontent.com/29737299/44976583-a28ad300-af33-11e8-8d94-132a33b0273e.png">
Here is an example for view.

**Comment by thescientist13** [comment]
I like it!  Feel for to submit a PR or ask any questions if you have them.  🙏

**Comment by Aimeelynnramirez** [comment]
@thescientist13
@New Branch #20 [ https://github.com/ProjectEvergreen/projectevergreen.github.io/pull/20](url)

**Comment by aholtzman** [comment]
did a first iteration of design changes to line up with Greenwood - simple reskin https://github.com/ProjectEvergreen/projectevergreen.github.io/tree/issue3_designAndLayout
