### ISSUE TITLE
[Security] Workflow ci.yml is using vulnerable action actions/checkout

### ISSUE THREAD

**Issue by Freakston** [ProjectEvergreen/projectevergreen.github.io#76]
The workflow ci.yml is referencing action actions/checkout using references v1. However this reference is missing the commit [a6747255bd19d7a757dbdda8c654a9f84db19839](https://github.com/actions/checkout/commits/a6747255bd19d7a757dbdda8c654a9f84db19839) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by thescientist13** [comment]
Hey @Freakston , thanks for looking into this!  👀 

It appears [this repo](https://github.com/ProjectEvergreen/projectevergreen.github.io/blob/master/.github/workflows/ci.yml) is using `actions/checkout@v2` but one of my teammates did observe that we are still using `v1` in our main project [Greenwood's actions](https://github.com/ProjectEvergreen/greenwood/tree/master/.github/workflows), which maybe was the repo you were looking for?

If you felt like opening a PR, I can transfer this issue to that repo and we can continue the conversation and PR review there.
